name: E2E tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e:
    runs-on: ubuntu-latest
    services:
      mongo:
        image: mongo:6
        options: >-
          --health-cmd "mongo --eval 'db.adminCommand(\"ping\")'" --health-interval 10s --health-timeout 5s --health-retries 5
        ports:
          - 27017:27017
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Start server
        env:
          MONGO_URI: mongodb://localhost:27017/ci-test
          PORT: 3000
        run: |
          npm start &
          # wait for server to be up
          for i in {1..30}; do
            if curl -sS http://localhost:3000/ >/dev/null; then echo "server up" && break; fi
            sleep 1
          done

      - name: Run Playwright E2E
        run: npm run test:e2e
